version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./laravel:/work

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'phper'
      PMA_PASSWORD: 'secret'
    ports:
      - '8081:80'

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

volumes:
  db-store:
    